# /coder/apps/config.yaml

# for jupyterlab reference: https://jupyterlab.readthedocs.io/en/stable/getting_started/starting.html
# for server start parameters like ServerApp.base_url https://jupyterlab-server.readthedocs.io/en/latest/api/app-config.html
apps:
  # Name of application in launcher. Name may consist of alphanumeric
  # characters, dashes, underscores. Names must begin with an alphanumeric
  # character. Names must be unique per application. Required.
  - name: jupyterlab
    # Application scheme - must be http or https. Required.
    scheme: http
    # Application port. Required.
    port: 8888
    # Host of the application to use when dialing. Defaults to localhost.
    # Optional.
    host: "localhost"
    # Working directory for the start command. Required.
    working-directory: /home/coder
    # File path to icon used in application launcher. Icons should be either
    # PNG, SVG, or JPG. Required.
    icon-path: /coder/apps/icon.png
    # Command to start the application. Required.
    command: jupyter-launcher
    # Array of arguments for command. Optional.
    args:
      - lab
      - --ServerApp.ip='*'
      - --ServerApp.token=''
      - --ServerApp.password=''
      - --ServerApp.base_url='./'
    # Health checks to get running application status. Can use exec or http
    # health checks to localhost. Optional, but we recommend specifying a
    # health check. If you don't supply one, then an http request is sent to
    # the application root path "/".
    health-check:
      exec:
        command: "pgrep"
        args:
          - jupyter-lab
      http:
        # Scheme must be "http" or "https". If not specified it inherits
        # the application scheme. Optional.
        scheme: "http"
        # The host to use when dialing the address. If not specified it
        # inherits the application host. Optional.
        host: "localhost"
        # Port to use when dialing the application. If not specified it
        # inherits the application port. Optional.
        port: 8888
        status-code: 302